"""create url table

Revision ID: 7258cb01dee9
Revises:
Create Date: 2026-03-09 16:58:40.763379

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "7258cb01dee9"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "url",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("original_url", sa.Text(), nullable=False),
        sa.Column("short_code", sa.String(length=16), nullable=False),
        sa.Column("clicks", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("url", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_url_short_code"), ["short_code"], unique=True
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("url", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_url_short_code"))

    op.drop_table("url")
    # ### end Alembic commands ###
