"""added CASCADE constraint to the URL model

Revision ID: ea377e46a373
Revises: 8d24c56ec93c
Create Date: 2026-03-13 12:27:22.666203

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "ea377e46a373"
down_revision = "8d24c56ec93c"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("url", schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f("url_user_id_fkey"), type_="foreignkey")
        batch_op.create_foreign_key(
            None, "user", ["user_id"], ["id"], ondelete="CASCADE"
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("url", schema=None) as batch_op:
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.create_foreign_key(
            batch_op.f("url_user_id_fkey"), "user", ["user_id"], ["id"]
        )

    # ### end Alembic commands ###
